apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/crnksl/kubevela-argocd
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
